/*
 Bgset - v2.0.0 - 2015-06-21  Lazysizes - v4.1.2 - 2018-10-09

The MIT License (MIT)

Copyright (c) 2015 Alexander Farkas

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
window.bgset=function(w,doc){function bgset(){var elements=getAllElements(),element,firstMatch;for(var i=0,len=elements.length;i<len;i++){element=elements[i];firstMatch=getMatch(element["rules"]);if(firstMatch)applyBg(firstMatch,element["dom"]);else applyBg(element["default"],element["dom"])}}function matchesMedia(media){return w.matchMedia&&w.matchMedia(media).matches}function getMatch(rules){var ruls=rules.match(/\[.*?\]/g),rule,bg,mq,match=undefined;for(var i=0,len=ruls.length;i<len;i++){rule=
ruls[i].slice(1,-1).split(", ");bg=rule.slice(0,-1).join("");mq=rule[rule.length-1];if(matchesMedia(mq)){match=bg;break}}return match}function applyBg(bg,element){var bgPath='url("'+bg+'")';if(element.style.backgroundImage!==bgPath)element.style.backgroundImage=bgPath}function getAllElements(){var elems=[],bgs=doc.querySelectorAll("[data-bgset]");for(var i=0,len=bgs.length;i<len;i++){var currBg=bgs[i],elem={};elem["rules"]=currBg.getAttribute("data-bgset");elem["dom"]=currBg.nextElementSibling;elem["default"]=
currBg.getAttribute("data-src");elems.push(elem)}return elems}function runBgSet(){bgset();var intervalId=setInterval(function(){bgset();if(/^loaded|^i|^c/.test(doc.readyState)){clearInterval(intervalId);return}},250);var resizeTimer;var handleResize=function(){bgset()};function checkResize(){clearTimeout(resizeTimer);resizeTimer=setTimeout(handleResize,60)}if(w.addEventListener)w.addEventListener("resize",checkResize,false);else if(w.attachEvent)w.attachEvent("onresize",checkResize)}runBgSet();return bgset}(window,
window.document);
(function(window,factory){var lazySizes=factory(window,window.document);window.lazySizes=lazySizes;if(typeof module=="object"&&module.exports)module.exports=lazySizes})(window,function l(window,document){if(!document.getElementsByClassName)return;var lazysizes,lazySizesConfig;var docElem=document.documentElement;var Date=window.Date;var supportPicture=window.HTMLPictureElement;var _addEventListener="addEventListener";var _getAttribute="getAttribute";var addEventListener=window[_addEventListener];var setTimeout=
window.setTimeout;var requestAnimationFrame=window.requestAnimationFrame||setTimeout;var requestIdleCallback=window.requestIdleCallback;var regPicture=/^picture$/i;var loadEvents=["load","error","lazyincluded","_lazyloaded"];var regClassCache={};var forEach=Array.prototype.forEach;var hasClass=function(ele,cls){if(!regClassCache[cls])regClassCache[cls]=new RegExp("(\\s|^)"+cls+"(\\s|$)");return regClassCache[cls].test(ele[_getAttribute]("class")||"")&&regClassCache[cls]};var addClass=function(ele,
cls){if(!hasClass(ele,cls))ele.setAttribute("class",(ele[_getAttribute]("class")||"").trim()+" "+cls)};var removeClass=function(ele,cls){var reg;if(reg=hasClass(ele,cls))ele.setAttribute("class",(ele[_getAttribute]("class")||"").replace(reg," "))};var addRemoveLoadEvents=function(dom,fn,add){var action=add?_addEventListener:"removeEventListener";if(add)addRemoveLoadEvents(dom,fn);loadEvents.forEach(function(evt){dom[action](evt,fn)})};var triggerEvent=function(elem,name,detail,noBubbles,noCancelable){var event=
document.createEvent("CustomEvent");if(!detail)detail={};detail.instance=lazysizes;event.initCustomEvent(name,!noBubbles,!noCancelable,detail);elem.dispatchEvent(event);return event};var updatePolyfill=function(el,full){var polyfill;if(!supportPicture&&(polyfill=window.picturefill||lazySizesConfig.pf)){if(full&&full.src&&!el[_getAttribute]("srcset"))el.setAttribute("srcset",full.src);polyfill({reevaluate:true,elements:[el]})}else if(full&&full.src)el.src=full.src};var getCSS=function(elem,style){return(getComputedStyle(elem,
null)||{})[style]};var getWidth=function(elem,parent,width){width=width||elem.offsetWidth;while(width<lazySizesConfig.minSize&&parent&&!elem._lazysizesWidth){width=parent.offsetWidth;parent=parent.parentNode}return width};var rAF=function(){var running,waiting;var firstFns=[];var secondFns=[];var fns=firstFns;var run=function(){var runFns=fns;fns=firstFns.length?secondFns:firstFns;running=true;waiting=false;while(runFns.length)runFns.shift()();running=false};var rafBatch=function(fn,queue){if(running&&
!queue)fn.apply(this,arguments);else{fns.push(fn);if(!waiting){waiting=true;(document.hidden?setTimeout:requestAnimationFrame)(run)}}};rafBatch._lsFlush=run;return rafBatch}();var rAFIt=function(fn,simple){return simple?function(){rAF(fn)}:function(){var that=this;var args=arguments;rAF(function(){fn.apply(that,args)})}};var throttle=function(fn){var running;var lastTime=0;var gDelay=lazySizesConfig.throttleDelay;var rICTimeout=lazySizesConfig.ricTimeout;var run=function(){running=false;lastTime=
Date.now();fn()};var idleCallback=requestIdleCallback&&rICTimeout>49?function(){requestIdleCallback(run,{timeout:rICTimeout});if(rICTimeout!==lazySizesConfig.ricTimeout)rICTimeout=lazySizesConfig.ricTimeout}:rAFIt(function(){setTimeout(run)},true);return function(isPriority){var delay;if(isPriority=isPriority===true)rICTimeout=33;if(running)return;running=true;delay=gDelay-(Date.now()-lastTime);if(delay<0)delay=0;if(isPriority||delay<9)idleCallback();else setTimeout(idleCallback,delay)}};var debounce=
function(func){var timeout,timestamp;var wait=99;var run=function(){timeout=null;func()};var later=function(){var last=Date.now()-timestamp;if(last<wait)setTimeout(later,wait-last);else(requestIdleCallback||run)(run)};return function(){timestamp=Date.now();if(!timeout)timeout=setTimeout(later,wait)}};(function(){var prop;var lazySizesDefaults={lazyClass:"lazyload",loadedClass:"lazyloaded",loadingClass:"lazyloading",preloadClass:"lazypreload",errorClass:"lazyerror",autosizesClass:"lazyautosizes",srcAttr:"data-src",
srcsetAttr:"data-srcset",sizesAttr:"data-sizes",minSize:40,customMedia:{},init:true,expFactor:1.5,hFac:.4,expand:100,loadMode:1,loadHidden:true,ricTimeout:0,throttleDelay:125};lazySizesConfig=window.lazySizesConfig||window.lazysizesConfig||{};for(prop in lazySizesDefaults)if(!(prop in lazySizesConfig))lazySizesConfig[prop]=lazySizesDefaults[prop];window.lazySizesConfig=lazySizesConfig;setTimeout(function(){if(lazySizesConfig.init)init()})})();var loader=function(){var preloadElems,isCompleted,resetPreloadingTimer,
loadMode,started;var eLvW,elvH,eLtop,eLleft,eLright,eLbottom;var defaultExpand,preloadExpand,hFac;var regImg=/^img$/i;var regIframe=/^iframe$/i;var supportScroll="onscroll"in window&&!/(gle|ing)bot/.test(navigator.userAgent);var shrinkExpand=0;var currentExpand=0;var isLoading=0;var lowRuns=-1;var resetPreloading=function(e){isLoading--;if(e&&e.target)addRemoveLoadEvents(e.target,resetPreloading);if(!e||isLoading<0||!e.target)isLoading=0};var isNestedVisible=function(elem,elemExpand){var outerRect;
var parent=elem;var visible=getCSS(document.body,"visibility")=="hidden"||getCSS(elem.parentNode,"visibility")!="hidden"&&getCSS(elem,"visibility")!="hidden";eLtop-=elemExpand;eLbottom+=elemExpand;eLleft-=elemExpand;eLright+=elemExpand;while(visible&&(parent=parent.offsetParent)&&parent!=document.body&&parent!=docElem){visible=(getCSS(parent,"opacity")||1)>0;if(visible&&getCSS(parent,"overflow")!="visible"){outerRect=parent.getBoundingClientRect();visible=eLright>outerRect.left&&eLleft<outerRect.right&&
eLbottom>outerRect.top-1&&eLtop<outerRect.bottom+1}}return visible};var checkElements=function(){var eLlen,i,rect,autoLoadElem,loadedSomething,elemExpand,elemNegativeExpand,elemExpandVal,beforeExpandVal;var lazyloadElems=lazysizes.elements;if((loadMode=lazySizesConfig.loadMode)&&isLoading<3&&(eLlen=lazyloadElems.length)){i=0;lowRuns++;if(preloadExpand==null){if(!("expand"in lazySizesConfig))lazySizesConfig.expand=docElem.clientHeight>500&&docElem.clientWidth>500?500:370;defaultExpand=lazySizesConfig.expand;
preloadExpand=defaultExpand*lazySizesConfig.expFactor}if(currentExpand<preloadExpand&&isLoading<1&&lowRuns>2&&loadMode>2&&!document.hidden){currentExpand=preloadExpand;lowRuns=0}else if(loadMode>1&&lowRuns>1&&isLoading<3)currentExpand=defaultExpand;else currentExpand=shrinkExpand;for(;i<eLlen;i++){if(!lazyloadElems[i]||lazyloadElems[i]._lazyRace)continue;if(!supportScroll){unveilElement(lazyloadElems[i]);continue}if(!(elemExpandVal=lazyloadElems[i][_getAttribute]("data-expand"))||!(elemExpand=elemExpandVal*
1))elemExpand=currentExpand;if(beforeExpandVal!==elemExpand){eLvW=innerWidth+elemExpand*hFac;elvH=innerHeight+elemExpand;elemNegativeExpand=elemExpand*-1;beforeExpandVal=elemExpand}rect=lazyloadElems[i].getBoundingClientRect();if((eLbottom=rect.bottom)>=elemNegativeExpand&&(eLtop=rect.top)<=elvH&&(eLright=rect.right)>=elemNegativeExpand*hFac&&(eLleft=rect.left)<=eLvW&&(eLbottom||eLright||eLleft||eLtop)&&(lazySizesConfig.loadHidden||getCSS(lazyloadElems[i],"visibility")!="hidden")&&(isCompleted&&isLoading<
3&&!elemExpandVal&&(loadMode<3||lowRuns<4)||isNestedVisible(lazyloadElems[i],elemExpand))){unveilElement(lazyloadElems[i]);loadedSomething=true;if(isLoading>3)break}else if(!loadedSomething&&isCompleted&&!autoLoadElem&&isLoading<3&&lowRuns<4&&loadMode>2&&(preloadElems[0]||lazySizesConfig.preloadAfterLoad)&&(preloadElems[0]||!elemExpandVal&&(eLbottom||eLright||eLleft||eLtop||lazyloadElems[i][_getAttribute](lazySizesConfig.sizesAttr)!="auto")))autoLoadElem=preloadElems[0]||lazyloadElems[i]}if(autoLoadElem&&
!loadedSomething)unveilElement(autoLoadElem)}};var throttledCheckElements=throttle(checkElements);var switchLoadingClass=function(e){addClass(e.target,lazySizesConfig.loadedClass);removeClass(e.target,lazySizesConfig.loadingClass);addRemoveLoadEvents(e.target,rafSwitchLoadingClass);triggerEvent(e.target,"lazyloaded")};var rafedSwitchLoadingClass=rAFIt(switchLoadingClass);var rafSwitchLoadingClass=function(e){rafedSwitchLoadingClass({target:e.target})};var changeIframeSrc=function(elem,src){try{elem.contentWindow.location.replace(src)}catch(e){elem.src=
src}};var handleSources=function(source){var customMedia;var sourceSrcset=source[_getAttribute](lazySizesConfig.srcsetAttr);if(customMedia=lazySizesConfig.customMedia[source[_getAttribute]("data-media")||source[_getAttribute]("media")])source.setAttribute("media",customMedia);if(sourceSrcset)source.setAttribute("srcset",sourceSrcset)};var lazyUnveil=rAFIt(function(elem,detail,isAuto,sizes,isImg){var src,srcset,parent,isPicture,event,firesLoad;if(!(event=triggerEvent(elem,"lazybeforeunveil",detail)).defaultPrevented){if(sizes)if(isAuto)addClass(elem,
lazySizesConfig.autosizesClass);else elem.setAttribute("sizes",sizes);srcset=elem[_getAttribute](lazySizesConfig.srcsetAttr);src=elem[_getAttribute](lazySizesConfig.srcAttr);if(isImg){parent=elem.parentNode;isPicture=parent&&regPicture.test(parent.nodeName||"")}firesLoad=detail.firesLoad||"src"in elem&&(srcset||src||isPicture);event={target:elem};if(firesLoad){addRemoveLoadEvents(elem,resetPreloading,true);clearTimeout(resetPreloadingTimer);resetPreloadingTimer=setTimeout(resetPreloading,2500);addClass(elem,
lazySizesConfig.loadingClass);addRemoveLoadEvents(elem,rafSwitchLoadingClass,true)}if(isPicture)forEach.call(parent.getElementsByTagName("source"),handleSources);if(srcset)elem.setAttribute("srcset",srcset);else if(src&&!isPicture)if(regIframe.test(elem.nodeName))changeIframeSrc(elem,src);else elem.src=src;if(isImg&&(srcset||isPicture))updatePolyfill(elem,{src:src})}if(elem._lazyRace)delete elem._lazyRace;removeClass(elem,lazySizesConfig.lazyClass);rAF(function(){if(!firesLoad||elem.complete&&elem.naturalWidth>
1){if(firesLoad)resetPreloading(event);else isLoading--;switchLoadingClass(event)}},true)});var unveilElement=function(elem){var detail;var isImg=regImg.test(elem.nodeName);var sizes=isImg&&(elem[_getAttribute](lazySizesConfig.sizesAttr)||elem[_getAttribute]("sizes"));var isAuto=sizes=="auto";if((isAuto||!isCompleted)&&isImg&&(elem[_getAttribute]("src")||elem.srcset)&&!elem.complete&&!hasClass(elem,lazySizesConfig.errorClass)&&hasClass(elem,lazySizesConfig.lazyClass))return;detail=triggerEvent(elem,
"lazyunveilread").detail;if(isAuto)autoSizer.updateElem(elem,true,elem.offsetWidth);elem._lazyRace=true;isLoading++;lazyUnveil(elem,detail,isAuto,sizes,isImg)};var onload=function(){if(isCompleted)return;if(Date.now()-started<999){setTimeout(onload,999);return}var afterScroll=debounce(function(){lazySizesConfig.loadMode=3;throttledCheckElements()});isCompleted=true;lazySizesConfig.loadMode=3;throttledCheckElements();addEventListener("scroll",function(){if(lazySizesConfig.loadMode==3)lazySizesConfig.loadMode=
2;afterScroll()},true)};return{_:function(){started=Date.now();lazysizes.elements=document.getElementsByClassName(lazySizesConfig.lazyClass);preloadElems=document.getElementsByClassName(lazySizesConfig.lazyClass+" "+lazySizesConfig.preloadClass);hFac=lazySizesConfig.hFac;addEventListener("scroll",throttledCheckElements,true);addEventListener("resize",throttledCheckElements,true);if(window.MutationObserver)(new MutationObserver(throttledCheckElements)).observe(docElem,{childList:true,subtree:true,
attributes:true});else{docElem[_addEventListener]("DOMNodeInserted",throttledCheckElements,true);docElem[_addEventListener]("DOMAttrModified",throttledCheckElements,true);setInterval(throttledCheckElements,999)}addEventListener("hashchange",throttledCheckElements,true);["focus","mouseover","click","load","transitionend","animationend","webkitAnimationEnd"].forEach(function(name){document[_addEventListener](name,throttledCheckElements,true)});if(/d$|^c/.test(document.readyState))onload();else{addEventListener("load",
onload);document[_addEventListener]("DOMContentLoaded",throttledCheckElements);setTimeout(onload,2E4)}if(lazysizes.elements.length){checkElements();rAF._lsFlush()}else throttledCheckElements()},checkElems:throttledCheckElements,unveil:unveilElement}}();var autoSizer=function(){var autosizesElems;var sizeElement=rAFIt(function(elem,parent,event,width){var sources,i,len;elem._lazysizesWidth=width;width+="px";elem.setAttribute("sizes",width);if(regPicture.test(parent.nodeName||"")){sources=parent.getElementsByTagName("source");
for(i=0,len=sources.length;i<len;i++)sources[i].setAttribute("sizes",width)}if(!event.detail.dataAttr)updatePolyfill(elem,event.detail)});var getSizeElement=function(elem,dataAttr,width){var event;var parent=elem.parentNode;if(parent){width=getWidth(elem,parent,width);event=triggerEvent(elem,"lazybeforesizes",{width:width,dataAttr:!!dataAttr});if(!event.defaultPrevented){width=event.detail.width;if(width&&width!==elem._lazysizesWidth)sizeElement(elem,parent,event,width)}}};var updateElementsSizes=
function(){var i;var len=autosizesElems.length;if(len){i=0;for(;i<len;i++)getSizeElement(autosizesElems[i])}};var debouncedUpdateElementsSizes=debounce(updateElementsSizes);return{_:function(){autosizesElems=document.getElementsByClassName(lazySizesConfig.autosizesClass);addEventListener("resize",debouncedUpdateElementsSizes)},checkElems:debouncedUpdateElementsSizes,updateElem:getSizeElement}}();var init=function(){if(!init.i){init.i=true;autoSizer._();loader._()}};lazysizes={cfg:lazySizesConfig,
autoSizer:autoSizer,loader:loader,init:init,uP:updatePolyfill,aC:addClass,rC:removeClass,hC:hasClass,fire:triggerEvent,gW:getWidth,rAF:rAF};return lazysizes});
window.Modernizr=function(window,document,undefined){var version="2.8.2",Modernizr={},enableClasses=true,docElement=document.documentElement,mod="modernizr",modElem=document.createElement(mod),mStyle=modElem.style,inputElem=document.createElement("input"),smile=":)",toString={}.toString,prefixes=" -webkit- -moz- -o- -ms- ".split(" "),omPrefixes="Webkit Moz O ms",cssomPrefixes=omPrefixes.split(" "),domPrefixes=omPrefixes.toLowerCase().split(" "),ns={"svg":"http://www.w3.org/2000/svg"},tests={},inputs=
{},attrs={},classes=[],slice=classes.slice,featureName,injectElementWithStyles=function(rule,callback,nodes,testnames){var style,ret,node,docOverflow,div=document.createElement("div"),body=document.body,fakeBody=body||document.createElement("body");if(parseInt(nodes,10))while(nodes--){node=document.createElement("div");node.id=testnames?testnames[nodes]:mod+(nodes+1);div.appendChild(node)}style=["\x26#173;",'\x3cstyle id\x3d"s',mod,'"\x3e',rule,"\x3c/style\x3e"].join("");div.id=mod;(body?div:fakeBody).innerHTML+=
style;fakeBody.appendChild(div);if(!body){fakeBody.style.background="";fakeBody.style.overflow="hidden";docOverflow=docElement.style.overflow;docElement.style.overflow="hidden";docElement.appendChild(fakeBody)}ret=callback(div,rule);if(!body){fakeBody.parentNode.removeChild(fakeBody);docElement.style.overflow=docOverflow}else div.parentNode.removeChild(div);return!!ret},testMediaQuery=function(mq){var matchMedia=window.matchMedia||window.msMatchMedia;if(matchMedia)return matchMedia(mq)&&matchMedia(mq).matches||
false;var bool;injectElementWithStyles("@media "+mq+" { #"+mod+" { position: absolute; } }",function(node){bool=(window.getComputedStyle?getComputedStyle(node,null):node.currentStyle)["position"]=="absolute"});return bool},isEventSupported=function(){var TAGNAMES={"select":"input","change":"input","submit":"form","reset":"form","error":"img","load":"img","abort":"img"};function isEventSupported(eventName,element){element=element||document.createElement(TAGNAMES[eventName]||"div");eventName="on"+eventName;
var isSupported=eventName in element;if(!isSupported){if(!element.setAttribute)element=document.createElement("div");if(element.setAttribute&&element.removeAttribute){element.setAttribute(eventName,"");isSupported=is(element[eventName],"function");if(!is(element[eventName],"undefined"))element[eventName]=undefined;element.removeAttribute(eventName)}}element=null;return isSupported}return isEventSupported}(),_hasOwnProperty={}.hasOwnProperty,hasOwnProp;if(!is(_hasOwnProperty,"undefined")&&!is(_hasOwnProperty.call,
"undefined"))hasOwnProp=function(object,property){return _hasOwnProperty.call(object,property)};else hasOwnProp=function(object,property){return property in object&&is(object.constructor.prototype[property],"undefined")};if(!Function.prototype.bind)Function.prototype.bind=function bind(that){var target=this;if(typeof target!="function")throw new TypeError;var args=slice.call(arguments,1),bound=function(){if(this instanceof bound){var F=function(){};F.prototype=target.prototype;var self=new F;var result=
target.apply(self,args.concat(slice.call(arguments)));if(Object(result)===result)return result;return self}else return target.apply(that,args.concat(slice.call(arguments)))};return bound};function setCss(str){mStyle.cssText=str}function setCssAll(str1,str2){return setCss(prefixes.join(str1+";")+(str2||""))}function is(obj,type){return typeof obj===type}function contains(str,substr){return!!~(""+str).indexOf(substr)}function testProps(props,prefixed){for(var i in props){var prop=props[i];if(!contains(prop,
"-")&&mStyle[prop]!==undefined)return prefixed=="pfx"?prop:true}return false}function testDOMProps(props,obj,elem){for(var i in props){var item=obj[props[i]];if(item!==undefined){if(elem===false)return props[i];if(is(item,"function"))return item.bind(elem||obj);return item}}return false}function testPropsAll(prop,prefixed,elem){var ucProp=prop.charAt(0).toUpperCase()+prop.slice(1),props=(prop+" "+cssomPrefixes.join(ucProp+" ")+ucProp).split(" ");if(is(prefixed,"string")||is(prefixed,"undefined"))return testProps(props,
prefixed);else{props=(prop+" "+domPrefixes.join(ucProp+" ")+ucProp).split(" ");return testDOMProps(props,prefixed,elem)}}tests["flexbox"]=function(){return testPropsAll("flexWrap")};tests["canvas"]=function(){var elem=document.createElement("canvas");return!!(elem.getContext&&elem.getContext("2d"))};tests["canvastext"]=function(){return!!(Modernizr["canvas"]&&is(document.createElement("canvas").getContext("2d").fillText,"function"))};tests["webgl"]=function(){return!!window.WebGLRenderingContext};
tests["touch"]=function(){var bool;if("ontouchstart"in window||window.DocumentTouch&&document instanceof DocumentTouch)bool=true;else injectElementWithStyles(["@media (",prefixes.join("touch-enabled),("),mod,")","{#modernizr{top:9px;position:absolute}}"].join(""),function(node){bool=node.offsetTop===9});return bool};tests["geolocation"]=function(){return"geolocation"in navigator};tests["postmessage"]=function(){return!!window.postMessage};tests["websqldatabase"]=function(){return!!window.openDatabase};
tests["indexedDB"]=function(){return!!testPropsAll("indexedDB",window)};tests["hashchange"]=function(){return isEventSupported("hashchange",window)&&(document.documentMode===undefined||document.documentMode>7)};tests["history"]=function(){return!!(window.history&&history.pushState)};tests["draganddrop"]=function(){var div=document.createElement("div");return"draggable"in div||"ondragstart"in div&&"ondrop"in div};tests["websockets"]=function(){return"WebSocket"in window||"MozWebSocket"in window};tests["rgba"]=
function(){setCss("background-color:rgba(150,255,150,.5)");return contains(mStyle.backgroundColor,"rgba")};tests["hsla"]=function(){setCss("background-color:hsla(120,40%,100%,.5)");return contains(mStyle.backgroundColor,"rgba")||contains(mStyle.backgroundColor,"hsla")};tests["multiplebgs"]=function(){setCss("background:url(https://),url(https://),red url(https://)");return/(url\s*\(.*?){3}/.test(mStyle.background)};tests["backgroundsize"]=function(){return testPropsAll("backgroundSize")};tests["borderimage"]=
function(){return testPropsAll("borderImage")};tests["borderradius"]=function(){return testPropsAll("borderRadius")};tests["boxshadow"]=function(){return testPropsAll("boxShadow")};tests["textshadow"]=function(){return document.createElement("div").style.textShadow===""};tests["opacity"]=function(){setCssAll("opacity:.55");return/^0.55$/.test(mStyle.opacity)};tests["cssanimations"]=function(){return testPropsAll("animationName")};tests["csscolumns"]=function(){return testPropsAll("columnCount")};
tests["cssgradients"]=function(){var str1="background-image:",str2="gradient(linear,left top,right bottom,from(#9f9),to(white));",str3="linear-gradient(left top,#9f9, white);";setCss((str1+"-webkit- ".split(" ").join(str2+str1)+prefixes.join(str3+str1)).slice(0,-str1.length));return contains(mStyle.backgroundImage,"gradient")};tests["cssreflections"]=function(){return testPropsAll("boxReflect")};tests["csstransforms"]=function(){return!!testPropsAll("transform")};tests["csstransforms3d"]=function(){var ret=
!!testPropsAll("perspective");if(ret&&"webkitPerspective"in docElement.style)injectElementWithStyles("@media (transform-3d),(-webkit-transform-3d){#modernizr{left:9px;position:absolute;height:3px;}}",function(node,rule){ret=node.offsetLeft===9&&node.offsetHeight===3});return ret};tests["csstransitions"]=function(){return testPropsAll("transition")};tests["fontface"]=function(){var bool;injectElementWithStyles('@font-face {font-family:"font";src:url("https://")}',function(node,rule){var style=document.getElementById("smodernizr"),
sheet=style.sheet||style.styleSheet,cssText=sheet?sheet.cssRules&&sheet.cssRules[0]?sheet.cssRules[0].cssText:sheet.cssText||"":"";bool=/src/i.test(cssText)&&cssText.indexOf(rule.split(" ")[0])===0});return bool};tests["generatedcontent"]=function(){var bool;injectElementWithStyles(["#",mod,"{font:0/0 a}#",mod,':after{content:"',smile,'";visibility:hidden;font:3px/1 a}'].join(""),function(node){bool=node.offsetHeight>=3});return bool};tests["video"]=function(){var elem=document.createElement("video"),
bool=false;try{if(bool=!!elem.canPlayType){bool=new Boolean(bool);bool.ogg=elem.canPlayType('video/ogg; codecs\x3d"theora"').replace(/^no$/,"");bool.h264=elem.canPlayType('video/mp4; codecs\x3d"avc1.42E01E"').replace(/^no$/,"");bool.webm=elem.canPlayType('video/webm; codecs\x3d"vp8, vorbis"').replace(/^no$/,"")}}catch(e){}return bool};tests["audio"]=function(){var elem=document.createElement("audio"),bool=false;try{if(bool=!!elem.canPlayType){bool=new Boolean(bool);bool.ogg=elem.canPlayType('audio/ogg; codecs\x3d"vorbis"').replace(/^no$/,
"");bool.mp3=elem.canPlayType("audio/mpeg;").replace(/^no$/,"");bool.wav=elem.canPlayType('audio/wav; codecs\x3d"1"').replace(/^no$/,"");bool.m4a=(elem.canPlayType("audio/x-m4a;")||elem.canPlayType("audio/aac;")).replace(/^no$/,"")}}catch(e){}return bool};tests["localstorage"]=function(){try{localStorage.setItem(mod,mod);localStorage.removeItem(mod);return true}catch(e){return false}};tests["sessionstorage"]=function(){try{sessionStorage.setItem(mod,mod);sessionStorage.removeItem(mod);return true}catch(e){return false}};
tests["webworkers"]=function(){return!!window.Worker};tests["applicationcache"]=function(){return!!window.applicationCache};tests["svg"]=function(){return!!document.createElementNS&&!!document.createElementNS(ns.svg,"svg").createSVGRect};tests["inlinesvg"]=function(){var div=document.createElement("div");div.innerHTML="\x3csvg/\x3e";return(div.firstChild&&div.firstChild.namespaceURI)==ns.svg};tests["smil"]=function(){return!!document.createElementNS&&/SVGAnimate/.test(toString.call(document.createElementNS(ns.svg,
"animate")))};tests["svgclippaths"]=function(){return!!document.createElementNS&&/SVGClipPath/.test(toString.call(document.createElementNS(ns.svg,"clipPath")))};function webforms(){Modernizr["input"]=function(props){for(var i=0,len=props.length;i<len;i++)attrs[props[i]]=!!(props[i]in inputElem);if(attrs.list)attrs.list=!!(document.createElement("datalist")&&window.HTMLDataListElement);return attrs}("autocomplete autofocus list placeholder max min multiple pattern required step".split(" "));Modernizr["inputtypes"]=
function(props){for(var i=0,bool,inputElemType,defaultView,len=props.length;i<len;i++){inputElem.setAttribute("type",inputElemType=props[i]);bool=inputElem.type!=="text";if(bool){inputElem.value=smile;inputElem.style.cssText="position:absolute;visibility:hidden;";if(/^range$/.test(inputElemType)&&inputElem.style.WebkitAppearance!==undefined){docElement.appendChild(inputElem);defaultView=document.defaultView;bool=defaultView.getComputedStyle&&defaultView.getComputedStyle(inputElem,null).WebkitAppearance!==
"textfield"&&inputElem.offsetHeight!==0;docElement.removeChild(inputElem)}else if(/^(search|tel)$/.test(inputElemType));else if(/^(url|email)$/.test(inputElemType))bool=inputElem.checkValidity&&inputElem.checkValidity()===false;else bool=inputElem.value!=smile}inputs[props[i]]=!!bool}return inputs}("search tel url email datetime date month week time datetime-local number range color".split(" "))}for(var feature in tests)if(hasOwnProp(tests,feature)){featureName=feature.toLowerCase();Modernizr[featureName]=
tests[feature]();classes.push((Modernizr[featureName]?"":"no-")+featureName)}Modernizr.input||webforms();Modernizr.addTest=function(feature,test){if(typeof feature=="object")for(var key in feature){if(hasOwnProp(feature,key))Modernizr.addTest(key,feature[key])}else{feature=feature.toLowerCase();if(Modernizr[feature]!==undefined)return Modernizr;test=typeof test=="function"?test():test;if(typeof enableClasses!=="undefined"&&enableClasses)docElement.className+=" mod-"+(test?"":"no-")+feature;Modernizr[feature]=
test}return Modernizr};setCss("");modElem=inputElem=null;(function(window,document){var version="3.7.0";var options=window.html5||{};var reSkip=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i;var saveClones=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i;var supportsHtml5Styles;var expando="_html5shiv";var expanID=0;var expandoData={};var supportsUnknownElements;(function(){try{var a=document.createElement("a");a.innerHTML=
"\x3cxyz\x3e\x3c/xyz\x3e";supportsHtml5Styles="hidden"in a;supportsUnknownElements=a.childNodes.length==1||function(){document.createElement("a");var frag=document.createDocumentFragment();return typeof frag.cloneNode=="undefined"||typeof frag.createDocumentFragment=="undefined"||typeof frag.createElement=="undefined"}()}catch(e){supportsHtml5Styles=true;supportsUnknownElements=true}})();function addStyleSheet(ownerDocument,cssText){var p=ownerDocument.createElement("p"),parent=ownerDocument.getElementsByTagName("head")[0]||
ownerDocument.documentElement;p.innerHTML="x\x3cstyle\x3e"+cssText+"\x3c/style\x3e";return parent.insertBefore(p.lastChild,parent.firstChild)}function getElements(){var elements=html5.elements;return typeof elements=="string"?elements.split(" "):elements}function getExpandoData(ownerDocument){var data=expandoData[ownerDocument[expando]];if(!data){data={};expanID++;ownerDocument[expando]=expanID;expandoData[expanID]=data}return data}function createElement(nodeName,ownerDocument,data){if(!ownerDocument)ownerDocument=
document;if(supportsUnknownElements)return ownerDocument.createElement(nodeName);if(!data)data=getExpandoData(ownerDocument);var node;if(data.cache[nodeName])node=data.cache[nodeName].cloneNode();else if(saveClones.test(nodeName))node=(data.cache[nodeName]=data.createElem(nodeName)).cloneNode();else node=data.createElem(nodeName);return node.canHaveChildren&&!reSkip.test(nodeName)&&!node.tagUrn?data.frag.appendChild(node):node}function createDocumentFragment(ownerDocument,data){if(!ownerDocument)ownerDocument=
document;if(supportsUnknownElements)return ownerDocument.createDocumentFragment();data=data||getExpandoData(ownerDocument);var clone=data.frag.cloneNode(),i=0,elems=getElements(),l=elems.length;for(;i<l;i++)clone.createElement(elems[i]);return clone}function shivMethods(ownerDocument,data){if(!data.cache){data.cache={};data.createElem=ownerDocument.createElement;data.createFrag=ownerDocument.createDocumentFragment;data.frag=data.createFrag()}ownerDocument.createElement=function(nodeName){if(!html5.shivMethods)return data.createElem(nodeName);
return createElement(nodeName,ownerDocument,data)};ownerDocument.createDocumentFragment=Function("h,f","return function(){"+"var n\x3df.cloneNode(),c\x3dn.createElement;"+"h.shivMethods\x26\x26("+getElements().join().replace(/[\w\-]+/g,function(nodeName){data.createElem(nodeName);data.frag.createElement(nodeName);return'c("'+nodeName+'")'})+");return n}")(html5,data.frag)}function shivDocument(ownerDocument){if(!ownerDocument)ownerDocument=document;var data=getExpandoData(ownerDocument);if(html5.shivCSS&&
!supportsHtml5Styles&&!data.hasCSS)data.hasCSS=!!addStyleSheet(ownerDocument,"article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}"+"mark{background:#FF0;color:#000}"+"template{display:none}");if(!supportsUnknownElements)shivMethods(ownerDocument,data);return ownerDocument}var html5={"elements":options.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output progress section summary template time video",
"version":version,"shivCSS":options.shivCSS!==false,"supportsUnknownElements":supportsUnknownElements,"shivMethods":options.shivMethods!==false,"type":"default","shivDocument":shivDocument,createElement:createElement,createDocumentFragment:createDocumentFragment};window.html5=html5;shivDocument(document)})(this,document);Modernizr._version=version;Modernizr._prefixes=prefixes;Modernizr._domPrefixes=domPrefixes;Modernizr._cssomPrefixes=cssomPrefixes;Modernizr.mq=testMediaQuery;Modernizr.hasEvent=isEventSupported;
Modernizr.testProp=function(prop){return testProps([prop])};Modernizr.testAllProps=testPropsAll;Modernizr.testStyles=injectElementWithStyles;Modernizr.prefixed=function(prop,obj,elem){if(!obj)return testPropsAll(prop,"pfx");else return testPropsAll(prop,obj,elem)};docElement.className=docElement.className.replace(/(^|\s)no-js(\s|$)/,"$1$2")+(enableClasses?" mod-js mod-"+classes.join(" mod-"):"");return Modernizr}(this,this.document);
(function(a,b,c){function d(a){return"[object Function]"==o.call(a)}function e(a){return"string"==typeof a}function f(){}function g(a){return!a||"loaded"==a||"complete"==a||"uninitialized"==a}function h(){var a=p.shift();q=1,a?a.t?m(function(){("c"==a.t?B.injectCss:B.injectJs)(a.s,0,a.a,a.x,a.e,1)},0):(a(),h()):q=0}function i(a,c,d,e,f,i,j){function k(b){if(!o&&g(l.readyState)&&(u.r=o=1,!q&&h(),l.onload=l.onreadystatechange=null,b)){"img"!=a&&m(function(){t.removeChild(l)},50);for(var d in y[c])y[c].hasOwnProperty(d)&&
y[c][d].onload()}}var j=j||B.errorTimeout,l=b.createElement(a),o=0,r=0,u={t:d,s:c,e:f,a:i,x:j};1===y[c]&&(r=1,y[c]=[]),"object"==a?l.data=c:(l.src=c,l.type=a),l.width=l.height="0",l.onerror=l.onload=l.onreadystatechange=function(){k.call(this,r)},p.splice(e,0,u),"img"!=a&&(r||2===y[c]?(t.insertBefore(l,s?null:n),m(k,j)):y[c].push(l))}function j(a,b,c,d,f){return q=0,b=b||"j",e(a)?i("c"==b?v:u,a,b,this.i++,c,d,f):(p.splice(this.i++,0,a),1==p.length&&h()),this}function k(){var a=B;return a.loader={load:j,
i:0},a}var l=b.documentElement,m=a.setTimeout,n=b.getElementsByTagName("script")[0],o={}.toString,p=[],q=0,r="MozAppearance"in l.style,s=r&&!!b.createRange().compareNode,t=s?l:n.parentNode,l=a.opera&&"[object Opera]"==o.call(a.opera),l=!!b.attachEvent&&!l,u=r?"object":l?"script":"img",v=l?"script":u,w=Array.isArray||function(a){return"[object Array]"==o.call(a)},x=[],y={},z={timeout:function(a,b){return b.length&&(a.timeout=b[0]),a}},A,B;B=function(a){function b(a){var a=a.split("!"),b=x.length,c=
a.pop(),d=a.length,c={url:c,origUrl:c,prefixes:a},e,f,g;for(f=0;f<d;f++)g=a[f].split("\x3d"),(e=z[g.shift()])&&(c=e(c,g));for(f=0;f<b;f++)c=x[f](c);return c}function g(a,e,f,g,h){var i=b(a),j=i.autoCallback;i.url.split(".").pop().split("?").shift(),i.bypass||(e&&(e=d(e)?e:e[a]||e[g]||e[a.split("/").pop().split("?")[0]]),i.instead?i.instead(a,e,f,g,h):(y[i.url]?i.noexec=!0:y[i.url]=1,f.load(i.url,i.forceCSS||!i.forceJS&&"css"==i.url.split(".").pop().split("?").shift()?"c":c,i.noexec,i.attrs,i.timeout),
(d(e)||d(j))&&f.load(function(){k(),e&&e(i.origUrl,h,g),j&&j(i.origUrl,h,g),y[i.url]=2})))}function h(a,b){function c(a,c){if(a)if(e(a))c||(j=function(){var a=[].slice.call(arguments);k.apply(this,a),l()}),g(a,j,b,0,h);else{if(Object(a)===a)for(n in m=function(){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(),a)a.hasOwnProperty(n)&&(!c&&!--m&&(d(j)?j=function(){var a=[].slice.call(arguments);k.apply(this,a),l()}:j[n]=function(a){return function(){var b=[].slice.call(arguments);a&&a.apply(this,
b),l()}}(k[n])),g(a[n],j,b,n,h))}else!c&&l()}var h=!!a.test,i=a.load||a.both,j=a.callback||f,k=j,l=a.complete||f,m,n;c(h?a.yep:a.nope,!!i),i&&c(i)}var i,j,l=this.yepnope.loader;if(e(a))g(a,0,l,0);else if(w(a))for(i=0;i<a.length;i++)j=a[i],e(j)?g(j,0,l,0):w(j)?B(j):Object(j)===j&&h(j,l);else Object(a)===a&&h(a,l)},B.addPrefix=function(a,b){z[a]=b},B.addFilter=function(a){x.push(a)},B.errorTimeout=1E4,null==b.readyState&&b.addEventListener&&(b.readyState="loading",b.addEventListener("DOMContentLoaded",
A=function(){b.removeEventListener("DOMContentLoaded",A,0),b.readyState="complete"},0)),a.yepnope=k(),a.yepnope.executeStack=h,a.yepnope.injectJs=function(a,c,d,e,i,j){var k=b.createElement("script"),l,o,e=e||B.errorTimeout;k.src=a;for(o in d)k.setAttribute(o,d[o]);c=j?h:c||f,k.onreadystatechange=k.onload=function(){!l&&g(k.readyState)&&(l=1,c(),k.onload=k.onreadystatechange=null)},m(function(){l||(l=1,c(1))},e),i?k.onload():n.parentNode.insertBefore(k,n)},a.yepnope.injectCss=function(a,c,d,e,g,i){var e=
b.createElement("link"),j,c=i?h:c||f;e.href=a,e.rel="stylesheet",e.type="text/css";for(j in d)e.setAttribute(j,d[j]);g||(n.parentNode.insertBefore(e,n),m(c,0))}})(this,document);Modernizr.load=function(){yepnope.apply(window,[].slice.call(arguments,0))};